<?xml version = '1.0'?>
<!DOCTYPE root [
<!ELEMENT root (tests, environment, robot, behaviour, display)>
<!ELEMENT tests (#PCDATA)>
<!ELEMENT environment (polygon*)>
<!ELEMENT polygon (vertex+)>
<!ELEMENT vertex EMPTY>
<!ELEMENT robot (start, moveRate, turnRate, lidarRate, noise)>
<!ELEMENT start (vertex)>
<!ELEMENT moveRate (#PCDATA)>
<!ELEMENT turnRate (#PCDATA)>
<!ELEMENT lidarRate (#PCDATA)>
<!ELEMENT noise (#PCDATA)>
<!ELEMENT behaviour (grid, strategy)>
<!ELEMENT grid (startGran, minGran, split)>
<!ELEMENT startGran (#PCDATA)>
<!ELEMENT minGran (#PCDATA)>
<!ELEMENT split (#PCDATA)>
<!ELEMENT strategy (#PCDATA)>
<!ELEMENT display (default, runtime)>
<!ELEMENT default (robotV?, lidarV?, obstaclesV?, beaconsV?, overlayV?, collisionV?,
detectorV?, ellipsesV?, pathV?, gridV?, mappingsV?, verticesV?, trackerV?, debugV?)>
<!ELEMENT robotV EMPTY>
<!ELEMENT lidarV EMPTY>
<!ELEMENT obstaclesV EMPTY>
<!ELEMENT beaconsV EMPTY>
<!ELEMENT overlayV EMPTY>
<!ELEMENT collisionV EMPTY>
<!ELEMENT detectorV EMPTY>
<!ELEMENT ellipsesV EMPTY>
<!ELEMENT pathV EMPTY>
<!ELEMENT gridV EMPTY>
<!ELEMENT mappingssV EMPTY>
<!ELEMENT verticesV EMPTY>
<!ELEMENT trackerV EMPTY>
<!ELEMENT quadrantsV EMPTY>
<!ELEMENT seekV EMPTY>
<!ELEMENT debugV EMPTY>
<!ELEMENT runtime (#PCDATA)>

<!ATTLIST environment width CDATA #REQUIRED>
<!ATTLIST environment height CDATA #REQUIRED>
<!ATTLIST polygon beacon (true|false) 'false'>
<!ATTLIST vertex x CDATA #REQUIRED>
<!ATTLIST vertex y CDATA #REQUIRED>
<!ATTLIST robot width CDATA #REQUIRED>
<!ATTLIST robot height CDATA #REQUIRED>
<!ATTLIST display width CDATA #REQUIRED>
<!ATTLIST display height CDATA #REQUIRED>
]>
<root>
	<tests>100</tests>
	<environment width = '50' height = '50'>
		<polygon>
			<vertex x = '10' y = '10'/>
			<vertex x = '11' y = '10'/>
			<vertex x = '11' y = '40'/>
			<vertex x = '10' y = '40'/>
		</polygon>
		<polygon>
			<vertex x = '11' y = '10'/>
			<vertex x = '11' y = '11'/>
			<vertex x = '40' y = '11'/>
			<vertex x = '40' y = '10'/>
		</polygon>
		<polygon>
			<vertex x = '37' y = '38'/>
			<vertex x = '37' y = '20'/>
			<vertex x = '38' y = '20'/>
			<vertex x = '38' y = '38'/>
		</polygon>
		<polygon>
			<vertex x = '26' y = '38'/>
			<vertex x = '26' y = '37'/>
			<vertex x = '37' y = '37'/>
			<vertex x = '37' y = '38'/>
		</polygon>
		<polygon>
			<vertex x = '24' y = '24'/>
			<vertex x = '25' y = '24'/>
			<vertex x = '25' y = '31'/>
			<vertex x = '24' y = '31'/>
		</polygon>
		<polygon>
			<vertex x = '25' y = '24'/>
			<vertex x = '25' y = '25'/>
			<vertex x = '31' y = '25'/>
			<vertex x = '31' y = '24'/>
		</polygon>
		<polygon>
			<vertex x = '23' y = '11'/>
			<vertex x = '24' y = '11'/>
			<vertex x = '24' y = '17'/>
			<vertex x = '23' y = '17'/>
		</polygon>
		<polygon>
			<vertex x = '11' y = '23'/>
			<vertex x = '11' y = '24'/>
			<vertex x = '17' y = '24'/>
			<vertex x = '17' y = '23'/>
		</polygon>
		<polygon>
			<vertex x = '11' y = '40'/>
			<vertex x = '11' y = '39'/>
			<vertex x = '20' y = '37'/>
			<vertex x = '20' y = '38'/>
		</polygon>
		<polygon>
			<vertex x = '31' y = '24'/>
			<vertex x = '31' y = '25'/>
			<vertex x = '37' y = '21'/>
			<vertex x = '37' y = '20'/>
		</polygon>
		<polygon beacon = 'true'>
			<vertex x = '38' y = '28'/>
			<vertex x = '38' y = '32'/>
			<vertex x = '40' y = '30'/>
		</polygon>
		<polygon beacon = 'true'>
			<vertex x = '37' y = '28'/>
			<vertex x = '37' y = '32'/>
			<vertex x = '35' y = '30'/>
		</polygon>
		<polygon>
			<vertex x = '24.5' y = '50'/>
			<vertex x = '25.5' y = '50'/>
			<vertex x = '25.5' y = '46'/>
			<vertex x = '24.5' y = '46'/>
		</polygon>
		<polygon beacon = 'true'>
			<vertex x = '0' y = '0'/>
			<vertex x = '4' y = '0'/>
			<vertex x = '0' y = '4'/>
		</polygon>
	</environment>
	<robot width = '1' height = '2'>
		<start>
			<vertex x = '5' y = '5'/>
		</start>
		<moveRate>10</moveRate>
		<turnRate>200</turnRate>
		<lidarRate>720</lidarRate>
		<noise>0.01</noise>
	</robot>
	<behaviour>
		<grid>
			<startGran>2</startGran>
			<minGran>0.4</minGran>
			<split>0.75</split>
		</grid>
		<strategy>1</strategy>
	</behaviour>
	<display width = '940' height = '940'>
		<default>
			<robotV />
			<lidarV />
			<obstaclesV />
			<beaconsV />
			<pathV />
			<gridV />
			<quadrantsV />
			<seekV />
		</default>
		<runtime>120</runtime>
	</display>
</root>